name: Generate Snake

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Aayush-gdeveloper
          outputs: github-contribution-grid-snake.svg

      - name: Push to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update snake animation"
